dna_sequence = "GTATATGCTACTACATGGTGACGGCGTGGTTTACAAGTTTGAATTGGGGCCGACAGATTGGGTGTTCGGTGTCAGGTGCTGTACTAGGTAGCCCCTTATTAATAGTCCTGCGCGTGTCAGCCTAACGTCTGCTGTAGAGGGTATGTTGGTGCACGCTGAGGTAATACCCCAGGCTCAATCCGCAGATTCCGTAACCTGCACTTGCGGGCTGCCTCGGCGCTGTCAGAGTCATCAGGGACATCTAAGATGTACGGGCACATGTCTGTCCACACACATGGGCTGCTAAATACCCGCAGCACAACCTCCGCGAGCTCTTATATAGATTTCCTGACCGAGAGTGAATCTAGGAATGCCCAATCCCAACTTGTGCATAGGCAGCAAATACTCGGCGCATGGTTTCCTGAGTTGGTTTACGTGGAGACTAAGGCCAATTGGATCAACGCGAGAGTTACAAAGCTAAGAAACCCGGACGCGTACCGAGTTGGACCTTCAGCTGCCAATTTGAATAATGATTAGGCCTTAACACAGGAGACTCCGCACGTTAAGTTCTGAGACTTGAAGTCTGACCTGTGTCCCAGAATCCACTCCCTTCACACTAGGTCACTTGTATAGCCTTAACGCATCATTGGCCTCGTCTCCTAGCTACAGGTCCATTGACCACTAACCGGATGCAAGTGACGTTCTGGCCGAAGGGTATTGCTTTTCTCACTCTGGTCCTACCGTCCAGCAGCCCGTTGCAACACATTCGGTTTATCTCCACTATTCACTGCCCGCGATGGAGATCGAATCTTATTAAAGATACTATTAACCCAACATACAACAACTGCGAGTCCCGCCCCGCCCATACTGTCGAATGTCTTTAGGTTGCTACTCCGCAATGTGGCTAGGTCTGTTAGTATGTTGGTAATGCGTGAGCGCGCTCAGTACTTGCCACAATCATCATCCATTTCGCTATGGCCCACTTGACGGC"
reverse_complement = ""

for nucleotide in dna_sequence[::-1]:
    match nucleotide:
        case 'A':
            reverse_complement += 'T'
        case 'T':
            reverse_complement += 'A'
        case 'C':
            reverse_complement += 'G'
        case 'G':
            reverse_complement += 'C'

print(reverse_complement)
